routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Product;
use App\Http\Controllers\PhotoController;
use App\Http\Controllers\Weather;
use App\Http\Controllers\Cart;
use App\Http\Controllers\AdminCategory;
use App\Http\Controllers\AdminProduct;
use App\Http\Controllers\Order;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::view('/', 'welcome', ["message" => "Hello!"]);

Route::middleware(['auth'])->group(function () {
    Route::prefix('products')->group(function () {
        Route::get('/{category_id?}', [Product::class, 'index'])->name('products')->whereNumber("category_id");
        Route::post('/add', [Product::class, 'add'])->name('products.add');
    });

    Route::prefix('cart')->group(function () {
        Route::get('/', [Cart::class, 'index'])->name('cart');
        Route::post('/add', [Cart::class, 'add'])->name('cart.add');
        Route::post('/update', [Cart::class, 'update'])->name('cart.update');
    });

    Route::prefix('order')->group(function () {
        Route::get('/', [Order::class, 'index'])->name('order');
        Route::post('/create', [Order::class, 'create'])->name('cart.create');
        Route::get('/thankyou/{order}', [Order::class, 'thankyou'])->name('order.thankyou');
        Route::get('/export', [Order::class, 'export'])->name('order.export');
    });

    Route::middleware(['admin.check:admin'])->group(function () {
        Route::resource('admin_category', AdminCategory::class);
        Route::resource('admin_product', AdminProduct::class);
    });
});

Route::resource('photos', PhotoController::class);

Route::prefix('weather')->group(function () {
    Route::get('/', [Weather::class, 'index'])->name('weather');
    Route::post('/store', [Weather::class, 'store'])->name('weather.store');
    Route::get('/city/{city}', [Weather::class, 'city'])->name('weather.city');
});

Auth::routes();

app/Http/Controllers/AdminProduct.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Product;
use App\Models\Category;
use App\Http\Requests\ProductAddRequest;
use App\Http\Requests\ProductEditRequest;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;

class AdminProduct extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin_product.index', [
            "products" => Product::all()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view(
            'admin_product.create',
            [
                "categories" => Category::all()
            ]
        );
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProductAddRequest $request)
    {
        if ($files = $request->file('img')) {
            $imgName =  Auth::id() . "_" . time() . "." . $files->getClientOriginalExtension();
            $files->storeAs(
                'public/products_img',
                $imgName
            );
        }
        $data = $request->all();
        $data['img'] = $imgName;
        $product = Product::create(
            $data
        );
        return redirect()->route('admin_product.index')->with(
            'status',
            'Product #' . $product->id . ' was created!'
        );
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('admin_product.show', [
            "product" => Product::find($id)
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('admin_product.edit', [
            "product" => Product::find($id),
            "categories" => Category::all()
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ProductEditRequest $request, $id)
    {
        $data = $request->except(['_token', '_method', 'img']);
        if ($files = $request->file('img')) {
            //old file can be deleted here by getting file name from model
            //Storage::delete(storage_path('app/public/products_img') . DIRECTORY_SEPARATOR . Product::find($id)->img);
            if (file_exists(storage_path('app/public/products_img') . DIRECTORY_SEPARATOR . Product::find($id)->img)) {
                unlink(storage_path('app/public/products_img') . DIRECTORY_SEPARATOR . Product::find($id)->img);
            }
            $imgName =  Auth::id() . "_" . time() . "." . $files->getClientOriginalExtension();
            $files->storeAs(
                'public/products_img',
                $imgName
            );
            $data['img'] = $imgName;
        }
        Product::updateData($id, $data);
        return redirect()->route('admin_product.index')->with(
            'status',
            'Product #' . $id . ' was updated!'
        );
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin_product/create.blade.php
@extends('adminlte::page')

@section('content')
    <div class="row">
        <div class="col-md-12">
            <!-- general form elements -->
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">Add New Product</h3>
                </div>
                <!-- /.card-header -->
                <!-- form start -->
                <form method="POST" enctype="multipart/form-data" action="{{ route('admin_product.store') }}">
                    @csrf
                    <div class="card-body">
                        <div class="form-group">
                            <label for="exampleInputTtitle">Product Title</label>
                            <input type="text" class="form-control @error('title') is-invalid @enderror"
                                   value="{{ old('title') }}" name="title" id="exampleInputTtitle"
                                   placeholder="Enter title">
                            @error('title')
                            <br>
                            <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="exampleInputSku">Sku</label>
                            <input type="text" class="form-control @error('sku') is-invalid @enderror"
                                   value="{{ old('sku') }}" name="sku" id="exampleInputSku" placeholder="Enter Sku">
                            @error('sku')
                            <br>
                            <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="exampleInputDescription">Description</label>
                            <textarea class="form-control @error('description') is-invalid @enderror" name="description"
                                      id="exampleInputDescription"
                                      placeholder="Enter Description">{{ old('description') }}</textarea>
                            @error('description')
                            <br>
                            <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="exampleInputPrice">Price</label>
                            <input type="text" class="form-control @error('price') is-invalid @enderror"
                                   value="{{ old('price') }}" name="price" id="exampleInputPrice" placeholder="Enter price">
                            @error('price')
                            <br>
                            <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="exampleInputQuantity">Quantity</label>
                            <input type="number" min="1" class="form-control @error('quantity') is-invalid @enderror"
                                   value="{{ old('price') }}" name="quantity" id="exampleInputQuantity" placeholder="Enter Quantity">
                            @error('quantity')
                            <br>
                            <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="exampleInputCategory">Category</label>
                            <select name="category_id" id="exampleInputCategory" class="form-control @error('category_id') is-invalid @enderror">
                                <option>Please select Category</option>
                                @foreach($categories as $category)
                                    <option @if(old('category_id') && old('category_id') == $category->id) selected @endif value="{{ $category->id }}">{{ $category->title }}</option>
                                @endforeach
                            </select>
                            @error('category_id')
                            <br>
                            <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="exampleInputFile">Product Image</label>
                            <div class="input-group">
                                <div class="custom-file">
                                    <input type="file" name="img" class="custom-file-input @error('img') is-invalid @enderror" id="exampleInputFile">
                                    <label class="custom-file-label" for="exampleInputFile">Choose file</label>
                                </div>
                                <div class="input-group-append">
                                    <span class="input-group-text">Upload</span>
                                </div>
                            </div>
                            @error('img')
                            <br>
                            <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>
                    <!-- /.card-body -->

                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Add</button>
                    </div>
                </form>
            </div>
            <!-- /.card -->
        </div>
    </div>
@endsection

@section('js')
@endsection

resources/views/admin_product/edit.blade.php
@extends('adminlte::page')

@section('content')
    <div class="row">
        <div class="col-md-12">
            <!-- general form elements -->
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">Edit Product</h3>
                </div>
                <!-- /.card-header -->
                <!-- form start -->
                <form method="POST" action="{{ route('admin_product.update', ["admin_product" => $product->id]) }}" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')
                    <div class="card-body">
                        <div class="form-group">
                            <label for="exampleInputTtitle">Product Title</label>
                            <input type="text" class="form-control @error('title') is-invalid @enderror"
                                   value="{{ old('title') ?? $product->title }}" name="title" id="exampleInputTtitle"
                                   placeholder="Enter title">
                            @error('title')
                            <br>
                            <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="exampleInputSku">Sku</label>
                            <input type="text" class="form-control @error('sku') is-invalid @enderror"
                                   value="{{ old('sku') ?? $product->sku }}" name="sku" id="exampleInputSku" placeholder="Enter Sku">
                            @error('sku')
                            <br>
                            <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="exampleInputDescription">Description</label>
                            <textarea class="form-control @error('description') is-invalid @enderror" name="description"
                                      id="exampleInputDescription"
                                      placeholder="Enter Description">{{ old('description') ?? $product->description }}</textarea>
                            @error('description')
                            <br>
                            <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="exampleInputPrice">Price</label>
                            <input type="text" class="form-control @error('price') is-invalid @enderror"
                                   value="{{ old('price') ?? $product->price }}" name="price" id="exampleInputPrice" placeholder="Enter price">
                            @error('price')
                            <br>
                            <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="exampleInputQuantity">Quantity</label>
                            <input type="number" min="1" class="form-control @error('quantity') is-invalid @enderror"
                                   value="{{ old('quantity') ?? $product->quantity }}" name="quantity" id="exampleInputQuantity" placeholder="Enter Quantity">
                            @error('quantity')
                            <br>
                            <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="exampleInputCategory">Category</label>
                            <select name="category_id" id="exampleInputCategory" class="form-control @error('category_id') is-invalid @enderror">
                                <option>Please select Category</option>
                                @foreach($categories as $category)
                                    <option @if((old('category_id') && old('category_id') == $category->id) || $category->id == $product->category_id) selected @endif value="{{ $category->id }}">{{ $category->title }}</option>
                                @endforeach
                            </select>
                            @error('category_id')
                            <br>
                            <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="exampleInputFile">Current Product Image</label>
                            <div class="col-4">
                                <img src="/storage/products_img/{{ $product->img }}" class="product-image" alt="Product Image">
                            </div>
                            <label for="exampleInputFile">Upload New Product Image</label>
                            <div class="input-group">
                                <div class="custom-file">
                                    <input type="file" name="img" class="custom-file-input @error('img') is-invalid @enderror" id="exampleInputFile">
                                    <label class="custom-file-label" for="exampleInputFile">Choose file</label>
                                </div>
                                <div class="input-group-append">
                                    <span class="input-group-text">Upload</span>
                                </div>
                            </div>
                            @error('img')
                            <br>
                            <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>
                    <!-- /.card-body -->

                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>
                </form>
            </div>
            <!-- /.card -->
        </div>
    </div>
@endsection

@section('js')
@endsection

resources/views/admin_product/index.blade.php
@extends('adminlte::page')

@section('css')
    <link href="{{ asset('css/custom.css') }}" rel="stylesheet">
@stop

@section('content')
    @if (session('status'))
        <div class="alert alert-success">
            {{ session('status') }}
        </div>
    @endif
    <br>
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">List of all products</h3>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <div id="example2_wrapper" class="dataTables_wrapper dt-bootstrap4">
                        <div class="row">
                            <div class="col-sm-12 col-md-6"></div>
                            <div class="col-sm-12 col-md-6"></div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12">
                                <table id="example2" class="table-striped table table-bordered table-hover" role="grid"
                                       aria-describedby="example2_info">
                                    <thead>
                                    <tr role="row">
                                        <th>#</th>
                                        <th>Title</th>
                                        <th>Category</th>
                                        <th>Price</th>
                                        <th>Quantity</th>
                                        <th>Actions</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($products as $product)
                                    <tr role="row">
                                        <td>{{ $product->id }}</td>
                                        <td><a href="{{ route('admin_product.show', ["admin_product" => $product->id]) }}">{{ $product->title }}</a></td>
                                        <td>{{ $product->category->title }}</td>
                                        <td>{{ $product->price }}</td>
                                        <td>{{ $product->quantity }}</td>
                                        <td>
                                            <a class="btn btn-block btn-info btn-sm"
                                               href="{{ route('admin_product.edit', ["admin_product" => $product->id]) }}">Edit</a>
                                            <form action="{{ route('admin_product.destroy', ["admin_product" => $product->id]) }}" method="POST">
                                                @csrf
                                                @method('DELETE')
                                                <input class="btn btn-block btn-danger btn-sm" type="submit" value="Delete">
                                            </form>
                                        </td>
                                    </tr>
                                    @endforeach
                                    </tbody>
                                    <tfoot>
                                    <tr>
                                        <th rowspan="1" colspan="1">#</th>
                                        <th rowspan="1" colspan="1">Title</th>
                                        <th rowspan="1" colspan="1">Created At</th>
                                        <th rowspan="1" colspan="1">Actions</th>
                                    </tr>
                                    </tfoot>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </div>
        <!-- /.col -->
    </div>

@endsection

@section('js')
<script>
    $(function () {
        $('#example2').DataTable({
            "paging": true,
            "lengthChange": false,
            "searching": true,
            "ordering": true,
            "info": true,
            "autoWidth": false,
        });
    });
</script>
@endsection

resources/views/admin_product/show.blade.php
@extends('adminlte::page')

@section('content')
    <div class="row">
        <div class="col-md-12">
            <!-- general form elements -->
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">Product Details</h3>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <div class="row">
                        <div class="col-12 col-sm-6">
                            <h3 class="d-inline-block d-sm-none">{{ $product->title }}</h3>
                            <div class="col-12">
                                <img src="/storage/products_img/{{ $product->img }}" class="product-image" alt="Product Image">
                            </div>
                        </div>
                        <div class="col-12 col-sm-6">
                            <h3 class="my-3">{{ $product->title }}</h3>
                            <p>{{ $product->description }}</p>

                            <hr>
                            <h4 class="mt-3">Quanity: {{ $product->quantity }}</h4>
                            <h4 class="mt-3">Category: {{ $product->category->title }}</h4>

                            <div class="bg-gray py-2 px-3 mt-4">
                                <h2 class="mb-0">
                                    ${{ $product->price }}
                                </h2>
                                <h4 class="mt-0">
                                    <small>SKU: {{ $product->sku }} </small>
                                </h4>
                            </div>

                            <div class="mt-4">
                                <a class="btn btn-primary btn-lg btn-flat" href="{{ route('admin_product.index') }}">Back</a>

                                <a class="btn btn-default btn-lg btn-flat" href="{{ route('admin_product.edit', ["admin_product" => $product->id]) }}">
                                    Edit
                                </a>
                            </div>


                        </div>
                    </div>
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </div>
    </div>
@endsection

@section('js')
@endsection