routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Product;
use App\Http\Controllers\PhotoController;
use App\Http\Controllers\Weather;
use App\Http\Controllers\Cart;
use App\Http\Controllers\AdminCategory;
use App\Http\Controllers\AdminProduct;
use App\Http\Controllers\Order;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::view('/', 'welcome', ["message" => "Hello!"]);

Route::middleware(['auth'])->group(function () {
    Route::prefix('products')->group(function () {
        Route::get('/{category_id?}', [Product::class, 'index'])->name('products')->whereNumber("category_id");
        Route::post('/add', [Product::class, 'add'])->name('products.add');
    });

    Route::prefix('cart')->group(function () {
        Route::get('/', [Cart::class, 'index'])->name('cart');
        Route::post('/add', [Cart::class, 'add'])->name('cart.add');
        Route::post('/update', [Cart::class, 'update'])->name('cart.update');
    });

    Route::prefix('order')->group(function () {
        Route::get('/', [Order::class, 'index'])->name('order');
        Route::post('/create', [Order::class, 'create'])->name('cart.create');
        Route::get('/thankyou/{order}', [Order::class, 'thankyou'])->name('order.thankyou');
        Route::get('/export', [Order::class, 'export'])->name('order.export');
    });

    Route::middleware(['admin.check:admin'])->group(function () {
        Route::resource('admin_category', AdminCategory::class);
        Route::resource('admin_product', AdminProduct::class);
    });
});

Route::resource('photos', PhotoController::class);

Route::prefix('weather')->group(function () {
    Route::get('/', [Weather::class, 'index'])->name('weather');
    Route::post('/store', [Weather::class, 'store'])->name('weather.store');
    Route::get('/city/{city}', [Weather::class, 'city'])->name('weather.city');
});

Auth::routes();

app/Http/Controllers/AdminCategory.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Category;
use App\Http\Requests\CategoryAddRequest;
use App\Http\Requests\CategoryEditRequest;
use Illuminate\Validation\Rule;

class AdminCategory extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin_category.index', [
            "categories" => Category::all()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin_category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategoryAddRequest $request)
    {
        $category = Category::create(
            $request->all()
        );
        return redirect()->route('admin_category.index')->with(
            'status',
            'Category #' . $category->id . ' was created!'
        );
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('admin_category.edit', [
            "category" => Category::find($id)
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CategoryEditRequest $request, $id)
    {
        Category::updateData($id, $request->title);
        return redirect()->route('admin_category.index')->with(
            'status',
            'Category #' . $id . ' was updated!'
        );
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Category::destroy($id);
        return redirect()->route('admin_category.index')->with(
            'status',
            'Category #' . $id . ' was deleted!'
        );
    }
}

resources/views/admin_category/create.blade.php
@extends('adminlte::page')

@section('content')
    <div class="row">
        <div class="col-md-12">
            <!-- general form elements -->
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">Add New Category</h3>
                </div>
                <!-- /.card-header -->
                <!-- form start -->
                <form method="POST" action="{{ route('admin_category.store') }}">
                    @csrf
                    <div class="card-body">
                        <div class="form-group">
                            <label for="exampleInputTtitle">Category Title</label>
                            <input type="text" class="form-control @error('title') is-invalid @enderror" value="{{ old('title') }}" name="title" id="exampleInputTtitle" placeholder="Enter title">
                            @error('title')
                                <br>
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>
                    <!-- /.card-body -->

                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Add</button>
                    </div>
                </form>
            </div>
            <!-- /.card -->
        </div>
    </div>
@endsection

@section('js')
@endsection

resources/views/admin_category/edit.blade.php
@extends('adminlte::page')

@section('content')
    <div class="row">
        <div class="col-md-12">
            <!-- general form elements -->
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">Edit Category</h3>
                </div>
                <!-- /.card-header -->
                <!-- form start -->
                <form method="POST" action="{{ route('admin_category.update', ["admin_category" => $category->id]) }}">
                    @csrf
                    @method('PUT')
                    <div class="card-body">
                        <div class="form-group">
                            <label for="exampleInputTtitle">Category Title</label>
                            <input type="text" class="form-control @error('title') is-invalid @enderror" value="{{ old('title') ?? $category->title }}" name="title" id="exampleInputTtitle" placeholder="Enter title">
                            @error('title')
                                <br>
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>
                    <!-- /.card-body -->

                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>
                </form>
            </div>
            <!-- /.card -->
        </div>
    </div>
@endsection

@section('js')
@endsection

resources/views/admin_category/index.blade.php
@extends('adminlte::page')

@section('css')
    <link href="{{ asset('css/custom.css') }}" rel="stylesheet">
@stop

@section('content')
    @if (session('status'))
        <div class="alert alert-success">
            {{ session('status') }}
        </div>
    @endif
    <br>
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">List of all categories</h3>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <div id="example2_wrapper" class="dataTables_wrapper dt-bootstrap4">
                        <div class="row">
                            <div class="col-sm-12 col-md-6"></div>
                            <div class="col-sm-12 col-md-6"></div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12">
                                <table id="example2" class="table-striped table table-bordered table-hover" role="grid"
                                       aria-describedby="example2_info">
                                    <thead>
                                    <tr role="row">
                                        <th>#</th>
                                        <th>Title</th>
                                        <th>
                                            Created At
                                        </th>
                                        <th>
                                            Actions
                                        </th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($categories as $category)
                                    <tr role="row">
                                        <td>{{ $category->id }}</td>
                                        <td>{{ $category->title }}</td>
                                        <td>{{ $category->created_at }}</td>
                                        <td>
                                            <a class="btn btn-block btn-info btn-sm"
                                               href="{{ route('admin_category.edit', ["admin_category" => $category->id]) }}">Edit</a>
                                            <!--<a class="btn btn-block btn-danger btn-sm"
                                               href="{{ route('admin_category.destroy', ["admin_category" => $category->id]) }}">Delete</a>-->
                                            <form action="{{ route('admin_category.destroy', ["admin_category" => $category->id]) }}" method="POST">
                                                @csrf
                                                @method('DELETE')
                                                <input class="btn btn-block btn-danger btn-sm" type="submit" value="Delete">
                                            </form>
                                        </td>
                                    </tr>
                                    @endforeach
                                    </tbody>
                                    <tfoot>
                                    <tr>
                                        <th rowspan="1" colspan="1">#</th>
                                        <th rowspan="1" colspan="1">Title</th>
                                        <th rowspan="1" colspan="1">Created At</th>
                                        <th rowspan="1" colspan="1">Actions</th>
                                    </tr>
                                    </tfoot>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </div>
        <!-- /.col -->
    </div>

@endsection

@section('js')
<script>
    $(function () {
        $('#example2').DataTable({
            "paging": true,
            "lengthChange": false,
            "searching": true,
            "ordering": true,
            "info": true,
            "autoWidth": false,
        });
    });
</script>
@endsection